people_with_wikipedia_articles = [
    "Albert Einstein",
    "Marie Curie",
    "Nelson Mandela",
    "Leonardo da Vinci",
    "Queen Elizabeth II",
    "Mahatma Gandhi",
    "Winston Churchill",
    "Steve Jobs",
    "Bill Gates",
    "Oprah Winfrey",
    "Elon Musk",
    "Serena Williams",
    "Barack Obama",
    "Malala Yousafzai",
    "Frida Kahlo",
    "Martin Luther King Jr.",
    "Amelia Earhart",
    "Pablo Picasso",
    "Mother Teresa",
    "Jeff Bezos",
    "Jane Goodall",
    "Stephen Hawking",
    "Mark Zuckerberg",
    "Michael Jordan",
    "Madonna",
    "William Shakespeare",
    "Marilyn Monroe",
    "David Beckham"
]